root = "."

tmp_dir = "tmp"

[build]
  bin = "./tmp/application"
  cmd = "go build -o ./tmp/application ."
  include_ext = ["go"]
  exclude_dir = ["vendor", "tmp", "cdk", "@cdk"]

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"

[runner]
  cmd = "APP_ENV=dev ./tmp/application"
